clasfw/clasfw/models.py
from ..models import Model, Amplitude, Channel, Quantity, Unit

clasfw/models/__init__.py
from .models import *

clasfw/clasfw/forms.py
from wtforms import Form, validators, widgets, \
    StringField, IntegerField, FloatField, BooleanField, SubmitField, \
    SelectField, SelectMultipleField, RadioField, FormField, HiddenField
from wtforms_alchemy.fields import QuerySelectField, QuerySelectMultipleField
from markupsafe import Markup
from .models import Channel, Quantity, Model
from .blueprint import qu


def sorted_by_pattern(arr, pattern, key=None):
    if key is None:
        key = lambda o: o
    def _keyfunc(o):
        try:
            idx = pattern.index(key(o))
        except ValueError:
            idx = float('Infinity')
        return idx
    return sorted(arr, key=_keyfunc)


def enabled_channels_factory():
    chs = Channel.query.filter_by(
        status=0
    ).order_by(
        Channel.priority.desc()
    )
    # fixme: temporary workaround
    return sorted_by_pattern(chs, [
        'pi+ n',
        'pi0 p',
        'pi- p',
        'pi0 n',
    ], key=lambda o: o.name)


def enabled_quantities_factory():
    return Quantity.query.filter_by(
        status=0
    ).filter(
        Quantity.name.in_(
            qu.respfunc_names +
                [q.name for q in qu.amplitudes])
    ).order_by(
        Quantity.priority.desc()
    )


def enabled_models_factory():
    return Model.query.filter_by(
        status=0
    ).order_by(
        Model.priority.desc()
    )


def get_html_plain_field(obj):
    return Markup(obj.html_plain)
def get_html_field(obj):
    # return obj.__html__()
    return Markup(obj.html)
    # return obj


class MinMaxForm(Form):
    min  = FloatField('min')
    step = FloatField('step')
    max  = FloatField('max')


def create_form(session, qu):
    class InterpolateForm(Form):
        quantity = QuerySelectField('Quantity',
            query_factory   = enabled_quantities_factory,
            option_widget   = widgets.RadioInput(),
            widget          = widgets.ListWidget(prefix_label=False),
            # widget          = widgets.TableWidget(),
            get_label       = get_html_field,
            default         = Quantity.by_name(qu.respfunc_names[0]),
            # default         = qu.respfuncs[0],
        )

        channel = QuerySelectField(
            query_factory   = enabled_channels_factory,
            # option_widget   = widgets.CheckboxInput(),
            option_widget   = widgets.RadioInput(),
            widget          = widgets.ListWidget(prefix_label=False),
            get_label       = get_html_field,
            # get_label       = get_html_plain_field,
            # fixme: no database connection yet when class is creating
            # default         = Channel.query.filter_by(name='inclusive').all(),
            # default         = [''],
            # default         = 'pi0 p',
            # default         = Channel.by_name('pi0 p'),  ##  fixme!
            default         = Channel.query.first(),  ##  fixme!
        )

        model = QuerySelectField('Model',
            [validators.DataRequired()],
            query_factory   = enabled_models_factory,
            option_widget   = widgets.RadioInput(),
            # option_widget   = Select2Widget(),
            widget          = widgets.ListWidget(prefix_label=False),
            # default         =  Model.query.order_by(Model.id.desc()).first(),  ##  fixme!
            default         =  Model.query.order_by(Model.id.desc()).first(),
        )

        # q2      = FormField(MinMaxForm, qu.Q2.html,
        #     widget = widgets.ListWidget(),
        #     default=dict(min=1, max=1, step=0.1))
        # w       = FormField(MinMaxForm, qu.W.html,
        #     widget = widgets.ListWidget(),
        #     default=dict(min=1.5, max=1.5, step=0.1))

        q2      = FloatField(qu.Q2.html,
            [validators.NumberRange(min=0)],
            default=0.5)
        w       = FloatField(qu.W.html,
            [validators.NumberRange(min=0)],
            default=1.5)

        varset  = HiddenField("Kinematic variables set",
            [validators.AnyOf([
                'cos_theta', 'theta', 't'
            ])],
            default="cos_theta")

        cos_theta = FormField(MinMaxForm, qu.cos_theta.html,
            widget = widgets.ListWidget(),
            default=dict(min=-1, max=1, step=0.1))
        theta = FormField(MinMaxForm, qu.theta.html,
            widget = widgets.ListWidget(),
            default=dict(min=0, max=180, step=10))
        t = FormField(MinMaxForm, qu.t.html,
            widget = widgets.ListWidget(),
            default=dict(min=-2, max=0, step=0.1))

        e_beam  = FloatField(qu.Eb.html,
            default=10.6)

        submit      = SubmitField("Interpolate")

    return InterpolateForm

clasfw/app.py
import os
from flask import Flask, render_template

from .settings import ProdConfig, DevConfig
from .extensions import db, migrate, assets, debug_toolbar
from .clasfw.blueprint import blueprint
from .clasfw import views, views_comparison, views_interpolate


def create_app(config_object=None):
    """An application factory"""

    if config_object is None:
        if os.environ.get('FLASK_ENV') == 'development':
            config_object = DevConfig
        # elif os.environ.get('FLASK_ENV') == 'production':
        else:
            config_object = ProdConfig

    app = Flask(__name__)
    # app.config.from_pyfile('settings.py')
    app.config.from_object(config_object)
    if os.environ.get('FLASK_ENV') in ('development', 'production'):
        app.config.from_pyfile('settings_local.py', silent=True)

    app.jinja_env.line_statement_prefix = '%'
    app.jinja_env.line_comment_prefix = '##'
    app.jinja_env.lstrip_blocks = True
    app.jinja_env.trim_blocks = True

    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_blueprints(app):
    app.register_blueprint(blueprint)


def register_extensions(app):
    db.init_app(app)
    migrate.init_app(app, db, render_as_batch=True)
    debug_toolbar.init_app(app)

    assets.init_app(app)

    # assets.debug = True
    # assets.append_path('assets')
    # assets.config['STYLUS_EXTRA_ARGS'] = [
    #     # Emits debug infos for the FireStylus Firebug plugin
    #     # '--firebug',
    #     # Emits comments in the generated CSS indicating
    #     # the corresponding Stylus line
    #     # '--line-numbers',
    # ]
    assets.register('css_screen',
        'base.styl',
        'views.styl',
        filters='stylus',
        output='gen/screen.css')

    assets.register('js_modellist',
        'model_list.js',
        output='gen/model_list.js')

    # if 0: #app.debug:
    #     from flask_debugtoolbar import DebugToolbarExtension
    #     debug_toolbar = DebugToolbarExtension()
    #     debug_toolbar.init_app(app)


def register_errorhandlers(app):

    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, "code", 500)
        return render_template("{0}.html".format(error_code)), error_code

    for errcode in [404, 500]:
    # for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)

clasfw/clasfw/blueprint.py
from functools import partial
from flask import Blueprint

import hep
import hep.amplitudes
from .models import Quantity, Amplitude, Unit
from ..utils import arxiv_url


blueprint = Blueprint("clasfw", __name__,
    template_folder='templates',
    static_folder='static')


@blueprint.app_template_filter()
def cpx(value):
    """
    Format complex or real value or None
    """
    return "{:.3g}".format(value) if value else value


class qu:
    respfunc_names = ["R_{}_00".format(i) for i in hep.amplitudes.strfun_indexes]
    dsigma_names = ["dsigma_{}/dOmega".format(i) for i in hep.amplitudes.strfun_indexes]
    respfuncs = []
    dsigmas = []
    amplitudes = []  ##  amplitudes list starting from 0, e. g. amplitudes[0]==H1, etc...

    @classmethod
    def respfunc_index(cls, q: Quantity):
        return cls.respfunc_names.index(q.name)

    @classmethod
    def amplitude_index(cls, q: Quantity):
        # ##  fixme!!! can fail if loaded `quantity` session differs from `qu.amplitudes` section
        # ##  models.dictionarymixin.__eq__ should be implemented, comparing __class__, id or name
        return [  ## index starting from 0!
            qq.name for qq in cls.amplitudes
        ].index(q.name)  ## fixme: temporary workaround

    @classmethod
    def load(cls):
        cls.Q2, cls.W, cls.cos_theta, cls.theta, cls.xB, cls.t, cls.phi, cls.dsigma, cls.Eb = (
            Quantity.by_name(s)
                for s in "Q^2 W cos(theta) theta x_B t phi dsigma/dOmega E_b".split() )
        cls.mcb_sr, cls.deg = (
            Unit.by_name(s)
                for s in "mcb/sr deg".split() )

        for s in cls.respfunc_names:
            q = Quantity.by_name(s)
            cls.respfuncs.append(q)

        for s in cls.dsigma_names:
            q = Quantity.by_name(s)
            cls.dsigmas.append(q)

        cls.amplitudes = Quantity.query.filter(
            Quantity.name.in_(
                'H_{}'.format(i)
                    for i in range(1, Amplitude.number+1)
            )
        ).order_by(Quantity.id).all()


@blueprint.before_app_first_request
def setup_quantities():
    qu.load()


@blueprint.context_processor
def inject_qu():
    return dict(
        qu=qu,
        zip=zip,
        arxiv_url=arxiv_url,
        hep=hep,
        partial=partial,
    )

clasfw/clasfw/views.py
from flask import current_app, request, render_template, abort
from sqlalchemy import func
from sqlalchemy.orm import exc
import numpy as np

import hep
import hep.amplitudes
from .blueprint import qu, blueprint as bp
from .models import Model, Amplitude, Channel
from ..utils import equal_eps, tex


@bp.route('/')
def index():
    return render_template('index.html')


@bp.route('/models')
def models_list():

    # from clasfw.extensions import db

    # sub_q = db.session.query(
    #     # Amplitude,
    #     Amplitude.model_id,
    #     func.count(Amplitude.model_id).label('count_ampl')
    # ).group_by(Amplitude.model_id).subquery()

    # sub_q = Amplitude.query(
    # .model_id,
    #     func.count(Amplitude.model_id).label('count_ampl')
    # ).group_by(Amplitude.model_id).subquery()

    # models = db.session.query(
    #     Model,
    #     Model.id,
    #     Model.name,
    #     Model.author,
    #     Model.description,
    #     sub_q.c.count_ampl
    # ).join(
    #     sub_q, sub_q.c.model_id == Model.id
    # ).all()

    models = Model.query.join(
        Amplitude
    ).group_by(Model.id).add_columns(
        func.count(Amplitude.id).label('count_ampl'),
        func.min(Amplitude.q2).label('q2_min'),
        func.max(Amplitude.q2).label('q2_max'),
        func.min(Amplitude.w).label('w_min'),
        func.max(Amplitude.w).label('w_max'),
    ).all()

    by_model_id = {}
    for mm in models:
        m = mm.Model
        prop = {}
        by_model_id[m.id] = prop
        prop['channels'] = Channel.query.distinct().join(Amplitude).filter(Amplitude.model==m)
        # prop['count_ampl'] = Amplitude.query.filter_by(model=m).count()
        # prop['count_ampl'] = Amplitude.query.filter_by(model=m).value( func.count(Amplitude.id) )

    # models = Model.query.add_columns(Model.id.label('count_ampl')).all()
    # print('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW')
    # m0 = models[0]
    # print(type(m0))
    # print(dir(m0))
    # print(dir(m0.Model))
    # print('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW')

    return render_template('models_list.html',
        models=models,
        by_model_id=by_model_id)


@bp.route('/model/<int:model_id>')
@bp.route('/model/<int:model_id>/p<int:page>')
def model_data(model_id, page=1):
    channel = request.args.get('channel', None)
    q2 = request.args.get('q2', default=None, type=float)
    model = Model.query.get_or_404(model_id)
    if channel:
        channel = Channel.query.get_or_404(channel)

    amplitudes = Amplitude.query.filter_by(model_id=model.id)
    if channel or q2:
        if channel:
            amplitudes = amplitudes.filter_by(channel_id=channel.id)
        if q2:
            amplitudes = amplitudes.filter(equal_eps(Amplitude.q2, q2))
    amplitudes = amplitudes.order_by(
        Amplitude.channel_id,  ##  fixme: use channel.priority
        Amplitude.q2,
        Amplitude.w,
        Amplitude.cos_theta.desc(),
    )
    # amplitudes = amplitudes.all()
    amplitudes = amplitudes.paginate(page, current_app.config['RECORDS_PER_PAGE'])

    return render_template('model_data.html',
        model=model,
        channel=channel,
        q2=q2,
        amplitudes=amplitudes,
    )


def plotly_3dlabel(q):
    try:
        return q.unicode
    except AttributeError:
        try:
            return q.name
        except AttributeError:
            pass
    return q.name


@bp.route('/dsigma')
def phi_dependence():
    channel_id= request.args.get('channel', type=int)
    model_id  = request.args.get('model', type=int)
    W         = request.args.get('w', type=float)
    Q2        = request.args.get('q2', type=float)
    cos_theta = request.args.get('cos_theta', type=float, default=None)
    Eb        = request.args.get('Eb', type=float, default=10.6)

    ampl = Amplitude.query.filter_by(
        channel_id=channel_id,
        model_id=model_id,
    ).filter(
        equal_eps(Amplitude.w, W),
        equal_eps(Amplitude.q2, Q2),
    )

    phi = np.linspace(0, 2*np.pi)
    eps_T = hep.ε_T(W, Q2, Eb)
    h=1

    if cos_theta is not None:  #  2D slice plot
        try:
            ampl = ampl.filter(
                equal_eps(Amplitude.cos_theta, cos_theta),
            ).one()
        except exc.NoResultFound:
            abort(404)

        respfuncs = hep.amplitudes.ampl_to_R(ampl.H)
        sig = hep.amplitudes.R_to_dsigma(
            W, Q2, eps_T, phi, h, respfuncs)

        plot = {
            'layout': {
                # 'autosize': 'true',
                'xaxis': {
                    'title': tex(qu.phi),
                },
                'yaxis': {
                    'title': tex(qu.dsigma),
                    'rangemode': 'tozero',
                },
                'margin': {
                     't': 32,
                     # 'b': 65,
                     # 'l': 65,
                     # 'r': 50,
                },
            },
            'data': [{
                'mode': 'markers',
                'type': 'scatter',
                'x': phi.tolist(),
                'y': sig.tolist(),
            }],
        }

        return render_template('phi_dependence.html',
            plot=plot,
            Eb=Eb,
            ampl=ampl,
            respfuncs=respfuncs,
            dsigmas=respfuncs*hep.amplitudes.R_to_dsigma_factor(ampl.w, ampl.q2),
        )
    else:  #  3D-plot
        ampls=ampl.all()
        if not ampls:
            abort(404)
        sig_M = np.zeros(shape=(len(ampls), len(phi)))
        cos_theta_v = np.zeros(shape=(len(ampls),))

        for i, ampl in enumerate(ampls):
            cos_theta = ampl.cos_theta
            cos_theta_v[i] = ampl.cos_theta
            sig = hep.amplitudes.H_to_dsigma(
                W, Q2, eps_T, phi, h, ampl.H)
            sig_M[i] = sig

        plot = {
            'layout': {
                'autosize': 'true',
                'width':  1000,
                'height': 800,

                'scene': {
                    # 'autosize': 'true',
                    'xaxis': {
                        'title': "φ, rad",  # fixme!
                    },
                    'yaxis': {
                        # 'title': plotly_3dlabel(qu.cos_theta),
                        'title': "cos θ",  # fixme!
                    },
                    'zaxis': {
                        # 'title': plotly_3dlabel(qu.dsigma),
                        'title': "dσ/dΩ, μb/sr",  # fixme!
                        'rangemode': 'tozero',
                    },
                },
            },
            'data': [{
                # 'mode': 'markers',
                'type': 'surface',
                'x': phi.tolist(),
                'y': cos_theta_v.tolist(),
                'z': sig_M.tolist(),
                'hovertemplate':
                    "φ: %{x} rad<br>"
                    "cos<i>θ</i>: %{y}<br>"
                    "dσ/dΩ: %{z} μb/sr"
                    "<extra></extra>",
            }],
        }

        return render_template('phi_dependence_3D.html',
            plot=plot,
            Eb=Eb,
            ampl=ampls[0],
        )


@bp.route('/groups')
@bp.route('/groups/p<int:page>')
def groups_list(page=1):
    models = Amplitude.query.join(
        Model, Channel
    ).group_by(
        Model.id, Channel.id, Amplitude.q2
    ).add_columns(
        func.count(Amplitude.id).label('count_ampl'),
        func.min(Amplitude.w).label('w_min'),
        func.max(Amplitude.w).label('w_max'),
    ).order_by(
        # Model.priority.desc(),
        Model.id, # fixme: temporary, use priority
        # Channel.priority.desc(),
        Channel.id, # fixme: temporary
        Amplitude.q2,
    ).paginate(page, current_app.config['RECORDS_PER_PAGE'])

    return render_template('groups_list.html',
        models=models)

clasfw/clasfw/templates/base.html
{# %- import "macros.html" as macros -% #}
<!doctype html>
<html lang="en">
<head>
<meta name="author" content="Vitaly Chesnokov">
<meta charset="utf-8">
<title>
{%- block fulltitle -%}
    {% block title %}{% endblock -%}
    {%- if self.title() %} // {# block 'title' is not empty #}{% endif -%}
    CLAS Analysis Framework
{%- endblock -%}
</title>
<script type="text/javascript"
    src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
{% assets "css_screen" -%}
    <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
{% endassets -%}

{% block extrahead %}{% endblock -%}

</head>
<body>
{% block body %}
{#
{{ macros.noscript() }}
#}

<div id="wrapper">
<div id="wrapper-row">

<div class="header">
    <h1>CLAS Analysis Framework</h1>
    {% include "topmenu.html" %}
</div>

<div class="content">
{% block content %}{% endblock %}
</div>

</div>

<div class="footer">
    <div class="powered">
        Created by
        <a href="http://www.sinp.msu.ru">SINP</a>
        <a href="https://www.msu.ru">MSU</a>,
        <a href="https://uconn.edu/">UCONN</a>,
        <a href="https://clasweb.jlab.org">CLAS Collaboration</a>
    </div>
</div>

</div>
{% endblock %}
</body>
</html>

clasfw/clasfw/templates/groups_list.html
{% extends "base.html" %}

{% block title -%}
	Data groups
{%- endblock %}

{% block extrahead %}
{% assets "js_modellist" -%}
<script src="{{ ASSET_URL }}"></script>
{% endassets -%}
{% endblock %}


{% block content %}
<h1>
	Data groups
</h1>

{{
	macros.render_pagination(models,
		partial(url_for, '.groups_list'))
}}

<table class="clickable models">
<thead>
<tr>
	<th class="hidden-link">Link</th>
	<th>Model</th>
	<th>Channel</th>
	<th>{{ qu.Q2.wu }}</th>
	<th>{{ qu.W.wu }}</th>
	<th>Data points</th>
</tr>
</thead>
{% for mm in models.items %}
{% set a = mm.Amplitude %}
<tr>
	<td class="hidden-link">
		<a href="{{
			url_for('.model_data',
				model_id=a.model_id, channel=a.channel_id, q2=a.q2)
		}}">group</a>
	</td>
	<td>
		{# <a href="{{ url_for('.model_data', model=a.model_id) }}"> #}
		{{ a.model.name }}
		{# </a> #}
	</td>
	<td>
		{{ a.channel }}
	</td>
	<td>{{ a.q2 }}</td>
	<td>
		{{ macros.range_if(mm.w_min, mm.w_max) }}
	</td>
	<td>
		{{ mm.count_ampl }}
	</td>
</tr>
{% endfor %}
</table>

{{
	macros.render_pagination(models,
		partial(url_for, '.groups_list'))
}}

{% endblock%}

clasfw/clasfw/templates/index.html
{% extends "base.html" %}

{% block extrahead %}
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        TeX: {
            equationNumbers: {
                autoNumber: 'AMS'
            },
            Macros: {
                d: "\\mathrm{d}"  //  differential sign
            }
        }
        {% if not config.DEBUG %}
        ,
        showMathMenu: false,
        {% endif %}
    });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_SVG"></script>
{% endblock %}

{% block content %}
<h1>
    CLAS Analysis Framework
</h1>
<ul>
    <li>
        <a href="{{ url_for('clasfw.models_list') }}">
            Available models list
        </a>
    </li>
    <li>
        <a href="{{ url_for('clasfw.groups_list') }}">
            Data grouped by model, channel, <span class="math">Q²</span> value
        </a>
    </li>
    <li>
        <a href="{{ url_for('clasfw.interpolate_form') }}">
            Data multivariate interpolation
        </a>
    </li>
</ul>

<div class="info">
<h2>Formalism used</h2>
<p>
    The differential cross-section of N&pi; electroproduction in the most general form can be presented as the following sum:
</p>
<p>
\begin{equation}
\frac{\d\sigma}{\d\Omega} =
                                        \frac{\d\sigma_{T  }}{\d\Omega}               +
    \varepsilon                         \frac{\d\sigma_{L  }}{\d\Omega}               +
    \sqrt{2\varepsilon(1+\varepsilon)}  \frac{\d\sigma_{TL }}{\d\Omega}  \cos \varphi +
    \varepsilon                         \frac{\d\sigma_{TT }}{\d\Omega}  \cos2\varphi +
   h\sqrt{2\varepsilon(1-\varepsilon)}  \frac{\d\sigma_{TL'}}{\d\Omega}  \sin \varphi
\end{equation}
</p>
<p>
\( \varepsilon \) stands for virtual photon polarization parameter
    (please, note: here we do NOT use the longitudinal polarization \( \varepsilon_L \) so the longitudinal cross-sections differ from those in <a href="#ref-1">[1]</a>),
\( h \) describes the longitudinal polarization of the incident electron:
\( h = +1(-1) \) if electrons are polarized parallel (anti-parallel) to the beam direction,
\( \varphi \) stands for meson emission angle,
\( \frac{\d\sigma_{i}}{\d\Omega} (i = T, L, TT, TL, TL&prime;) \) are related
to corresponding response functions \( R^{00}_{i} \) as follows:
</p>

\begin{align}
\frac{\d\sigma_{i  }}{\d\Omega} & = R^{00}_{i  } \frac{p_m}{k_{\gamma}^{cm}}
\end{align}

<p>
\( p_m \) is absolute value of meson three-momentum,
\( k_{\gamma}^{cm} \) is the photon equivalent energy in the CM-frame:
</p>

<p>
\begin{align}
    k_{\gamma}^{cm} & = \frac{W^2 - M_B^2}{2W}
\\
    p_m & = \sqrt{E_m^2 - m_m^2}
\\
    E_m & = \frac{W^2 + m_m^2 - M_B^2}{2W}
\end{align}
</p>

<p>
    \( E_m \) stands for meson energy in the CM-frame,
    \( m_m \) and \( M_B \) stand for meson and baryon masses,
    \( Q^2 \) is photon virtuality,
    \( W   \) is invariant mass of the final hadronic system.
</p>

<p>
    \( R^{00}_i (i = T, L, TT, TL, TL&prime;) \) are response functions:
</p>
<p>
\begin{align}
\begin{split}
	R^{00}_{T  }   & = \frac{1}{2}(|H_1|^2 + |H_2|^2 + |H_3|^2 + |H_4|^2)
\\
	R^{00}_{L  }   & = |H_5|^2 + |H_6|^2
\\
	R^{00}_{TL }   & = \frac{1}{\sqrt{2}}(H_5^*H_1 - H_5^*H_4 + H_6^*H_2 + H_6^*H_3)
\\
	R^{00}_{TT }   & = - H_1^*H_4 + H_2^*H_3
\\
	R^{00}_{TL'}   & = \frac{1}{\sqrt{2}}(-H_5^*H_1 + H_5^*H_4 - H_6^*H_2 - H_6^*H_3)
\end{split}
\end{align}
</p>

<p>
    \( H_i \; (i = 1..6) \) stand for helicity amplitudes.
</p>
</div>

<div>
<h2>References</h2>
<ol class="references">
    <li id="ref-1">
        <span class="authors">
            G. Knöchlein, D. Drechsel, L. Tiator
        </span>
        <span class="title">
            Photo- and Electroproduction of η-Mesons
        </span>
        <span class="ref">
            Z.Phys.A352 p.327-343, 1995
        </span>
        <a href="{{ arxiv_url('arXiv:nucl-th/9506029') }}">
            arXiv:nucl-th/9506029
        </a>
    </li>
</ol>
</div>
{% endblock%}

clasfw/clasfw/templates/interpolation_results.html
{% extends "phi_dependence_3D.html" %}

{% block title -%}
	Interpolation results
{%- endblock %}

{% block page_header %}
<h1>
	Interpolation results
</h1>
{% endblock%}

clasfw/clasfw/templates/models_list.html
{% extends "base.html" %}

{% block title -%}
	Models list
{%- endblock %}


{% block content %}
<h1>
	Reaction models for description of N&pi; electroproduction off nucleons
</h1>

<table class="models">
<thead>
<tr>
	<th>Name</th>
	<th>Author</th>
	<th>Description</th>
	<th>Channels</th>
	<th>{{ qu.Q2.wu }}</th>
	<th>{{ qu.W.wu }}</th>
	<th>Data points</th>
</tr>
</thead>
{% for mm in models %}
{% set m = mm.Model %}
<tr>
	<td>
		<a href="{{ url_for('.model_data', model_id=m.id) }}">
			{{ m.name }}
		</a>
	</td>
	<td>
		{{ m.author }}
	</td>
	<td>
		{{ m.description }}
	</td>
	<td class="channel">
		{% set comma = joiner(", ") %}
		{% for ch in by_model_id[m.id].channels %}
		{{ comma() }}
		<a href="{{
			url_for('.model_data', model_id=m.id, channel=ch.id)
		}}">
			{{ ch }}
		</a>
		{% endfor %}
	</td>
	<td>
		{{ macros.range_if(mm.q2_min, mm.q2_max) }}
	</td>
	<td>
		{{ macros.range_if(mm.w_min, mm.w_max) }}
	</td>
	<td>
		{{ mm.count_ampl }}
	</td>
</tr>
{% endfor %}
</table>
{% endblock%}